// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	GetStock(ctx context.Context, sku int32) (int64, error)
	ReleaseStock(ctx context.Context, arg ReleaseStockParams) (int64, error)
	ReserveStock(ctx context.Context, arg ReserveStockParams) (int64, error)
	UpsertStock(ctx context.Context, arg UpsertStockParams) error
}

var _ Querier = (*Queries)(nil)
