// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
)

const getStock = `-- name: GetStock :one
SELECT count
FROM loms.stocks
WHERE sku = $1
`

func (q *Queries) GetStock(ctx context.Context, sku int32) (int64, error) {
	row := q.db.QueryRow(ctx, getStock, sku)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const releaseStock = `-- name: ReleaseStock :execrows
UPDATE loms.stocks
SET count = count + $2
WHERE sku = $1
`

type ReleaseStockParams struct {
	Sku   int32 `json:"sku"`
	Count int64 `json:"count"`
}

func (q *Queries) ReleaseStock(ctx context.Context, arg ReleaseStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseStock, arg.Sku, arg.Count)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveStock = `-- name: ReserveStock :execrows
UPDATE loms.stocks
SET count = count - $2,
    updated_at = NOW()
WHERE sku = $1
  AND count >= $2
`

type ReserveStockParams struct {
	Sku   int32 `json:"sku"`
	Count int64 `json:"count"`
}

func (q *Queries) ReserveStock(ctx context.Context, arg ReserveStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveStock, arg.Sku, arg.Count)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertStock = `-- name: UpsertStock :exec
INSERT INTO loms.stocks (sku, count)
VALUES ($1, $2)
ON CONFLICT (sku) DO UPDATE SET count = EXCLUDED.count
`

type UpsertStockParams struct {
	Sku   int32 `json:"sku"`
	Count int64 `json:"count"`
}

func (q *Queries) UpsertStock(ctx context.Context, arg UpsertStockParams) error {
	_, err := q.db.Exec(ctx, upsertStock, arg.Sku, arg.Count)
	return err
}
