// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AddItem(ctx context.Context, arg AddItemParams) error
	DeleteItem(ctx context.Context, arg DeleteItemParams) error
	DeleteItemsByUserID(ctx context.Context, userID int64) error
	ListItemsByUserID(ctx context.Context, userID int64) ([]ListItemsByUserIDRow, error)
}

var _ Querier = (*Queries)(nil)
