// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
)

const addItem = `-- name: AddItem :exec
INSERT INTO cart.items (user_id, sku, count)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, sku) DO UPDATE SET count = cart.items.count + EXCLUDED.count
`

type AddItemParams struct {
	UserID int64 `json:"user_id"`
	Sku    int32 `json:"sku"`
	Count  int32 `json:"count"`
}

func (q *Queries) AddItem(ctx context.Context, arg AddItemParams) error {
	_, err := q.db.Exec(ctx, addItem, arg.UserID, arg.Sku, arg.Count)
	return err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM cart.items
WHERE user_id = $1
  AND sku = $2
`

type DeleteItemParams struct {
	UserID int64 `json:"user_id"`
	Sku    int32 `json:"sku"`
}

func (q *Queries) DeleteItem(ctx context.Context, arg DeleteItemParams) error {
	_, err := q.db.Exec(ctx, deleteItem, arg.UserID, arg.Sku)
	return err
}

const deleteItemsByUserID = `-- name: DeleteItemsByUserID :exec
DELETE FROM cart.items
WHERE user_id = $1
`

func (q *Queries) DeleteItemsByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteItemsByUserID, userID)
	return err
}

const listItemsByUserID = `-- name: ListItemsByUserID :many
SELECT sku, count
FROM cart.items
WHERE user_id = $1
ORDER BY sku
`

type ListItemsByUserIDRow struct {
	Sku   int32 `json:"sku"`
	Count int32 `json:"count"`
}

func (q *Queries) ListItemsByUserID(ctx context.Context, userID int64) ([]ListItemsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listItemsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsByUserIDRow
	for rows.Next() {
		var i ListItemsByUserIDRow
		if err := rows.Scan(&i.Sku, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
