// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimMessages = `-- name: ClaimMessages :many
UPDATE loms.outbox
SET status = 'in_progress',
    attempts = attempts + 1,
    updated_at = NOW()
WHERE id IN (
    SELECT id
    FROM loms.outbox
    WHERE status = 'created'
       OR (
            status = 'in_progress'
            AND updated_at + $1::interval < NOW()
       )
    ORDER BY created_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING idempotency_key, kind, payload
`

type ClaimMessagesParams struct {
	InProgressTtl pgtype.Interval `json:"in_progress_ttl"`
	BatchSize     int32           `json:"batch_size"`
}

type ClaimMessagesRow struct {
	IdempotencyKey string `json:"idempotency_key"`
	Kind           string `json:"kind"`
	Payload        []byte `json:"payload"`
}

func (q *Queries) ClaimMessages(ctx context.Context, arg ClaimMessagesParams) ([]ClaimMessagesRow, error) {
	rows, err := q.db.Query(ctx, claimMessages, arg.InProgressTtl, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimMessagesRow
	for rows.Next() {
		var i ClaimMessagesRow
		if err := rows.Scan(&i.IdempotencyKey, &i.Kind, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProcessed = `-- name: MarkProcessed :exec
UPDATE loms.outbox
SET status = 'processed',
    updated_at = NOW()
WHERE idempotency_key = ANY($1::text[])
`

func (q *Queries) MarkProcessed(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, markProcessed, dollar_1)
	return err
}

const markRetryable = `-- name: MarkRetryable :exec
UPDATE loms.outbox
SET status = 'created',
    updated_at = NOW()
WHERE idempotency_key = ANY($1::text[])
`

func (q *Queries) MarkRetryable(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, markRetryable, dollar_1)
	return err
}

const saveMessage = `-- name: SaveMessage :exec
INSERT INTO loms.outbox (idempotency_key, kind, payload)
VALUES (
    $1,
    $2,
    $3::jsonb
)
ON CONFLICT (idempotency_key) DO NOTHING
`

type SaveMessageParams struct {
	IdempotencyKey string `json:"idempotency_key"`
	Kind           string `json:"kind"`
	Payload        []byte `json:"payload"`
}

func (q *Queries) SaveMessage(ctx context.Context, arg SaveMessageParams) error {
	_, err := q.db.Exec(ctx, saveMessage, arg.IdempotencyKey, arg.Kind, arg.Payload)
	return err
}
