// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	ClaimMessages(ctx context.Context, arg ClaimMessagesParams) ([]ClaimMessagesRow, error)
	MarkProcessed(ctx context.Context, dollar_1 []string) error
	MarkRetryable(ctx context.Context, dollar_1 []string) error
	SaveMessage(ctx context.Context, arg SaveMessageParams) error
}

var _ Querier = (*Queries)(nil)
