// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (LomsOrder, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error
	DeleteOrder(ctx context.Context, id int64) error
	GetOrder(ctx context.Context, id int64) (LomsOrder, error)
	ListOrderItems(ctx context.Context, orderID int64) ([]ListOrderItemsRow, error)
	SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) (int64, error)
	TransitOrderStatus(ctx context.Context, arg TransitOrderStatusParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
