// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO loms.orders (user_id, status)
VALUES ($1, $2)
RETURNING id, user_id, status, created_at, updated_at
`

type CreateOrderParams struct {
	UserID int64           `json:"user_id"`
	Status LomsOrderStatus `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (LomsOrder, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.Status)
	var i LomsOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO loms.order_items (order_id, sku, count)
VALUES ($1, $2, $3)
`

type CreateOrderItemParams struct {
	OrderID int64 `json:"order_id"`
	Sku     int32 `json:"sku"`
	Count   int32 `json:"count"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem, arg.OrderID, arg.Sku, arg.Count)
	return err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM loms.orders
WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, status, created_at, updated_at
FROM loms.orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (LomsOrder, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i LomsOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT sku, count
FROM loms.order_items
WHERE order_id = $1
ORDER BY sku
`

type ListOrderItemsRow struct {
	Sku   int32 `json:"sku"`
	Count int32 `json:"count"`
}

func (q *Queries) ListOrderItems(ctx context.Context, orderID int64) ([]ListOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderItemsRow
	for rows.Next() {
		var i ListOrderItemsRow
		if err := rows.Scan(&i.Sku, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrderStatus = `-- name: SetOrderStatus :execrows
UPDATE loms.orders
SET status = $2,
    updated_at = NOW()
WHERE id = $1
`

type SetOrderStatusParams struct {
	ID     int64           `json:"id"`
	Status LomsOrderStatus `json:"status"`
}

func (q *Queries) SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setOrderStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const transitOrderStatus = `-- name: TransitOrderStatus :execrows
UPDATE loms.orders
SET status = $3,
    updated_at = NOW()
WHERE id = $1
  AND status = $2
`

type TransitOrderStatusParams struct {
	ID       int64           `json:"id"`
	Status   LomsOrderStatus `json:"status"`
	Status_2 LomsOrderStatus `json:"status_2"`
}

func (q *Queries) TransitOrderStatus(ctx context.Context, arg TransitOrderStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitOrderStatus, arg.ID, arg.Status, arg.Status_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
