-- +goose Up
-- +goose StatementBegin
CREATE TYPE loms.outbox_status AS ENUM ('created', 'in_progress', 'processed');

CREATE TABLE loms.outbox
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key TEXT                NOT NULL UNIQUE,
    kind            TEXT                NOT NULL,
    payload         JSONB               NOT NULL,
    status          loms.outbox_status  NOT NULL DEFAULT 'created',
    attempts        INTEGER             NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_loms_outbox_claim ON loms.outbox (status, updated_at, created_at);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS loms.outbox;
DROP TYPE IF EXISTS loms.outbox_status;
-- +goose StatementEnd
