-- +goose Up
-- +goose StatementBegin
CREATE SCHEMA IF NOT EXISTS loms;

CREATE TYPE loms.order_status AS ENUM (
    'new',
    'awaiting_payment',
    'failed',
    'paid',
    'cancelled'
);

CREATE TABLE loms.products
(
    sku        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT    NOT NULL,
    price      INTEGER NOT NULL CHECK (price > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE loms.stocks
(
    sku        INTEGER PRIMARY KEY,
    count      BIGINT      NOT NULL CHECK (count >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE loms.orders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT            NOT NULL,
    status     loms.order_status NOT NULL,
    created_at TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ       NOT NULL DEFAULT NOW()
);

CREATE TABLE loms.order_items
(
    order_id BIGINT  NOT NULL REFERENCES loms.orders (id) ON DELETE CASCADE,
    sku      INTEGER NOT NULL,
    count    INTEGER NOT NULL CHECK (count > 0),
    PRIMARY KEY (order_id, sku)
);

CREATE INDEX idx_loms_orders_user_id ON loms.orders (user_id);
CREATE INDEX idx_loms_order_items_sku ON loms.order_items (sku);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS loms.order_items;
DROP TABLE IF EXISTS loms.orders;
DROP TABLE IF EXISTS loms.stocks;
DROP TABLE IF EXISTS loms.products;
DROP TYPE IF EXISTS loms.order_status;
DROP SCHEMA IF EXISTS loms;
-- +goose StatementEnd
