// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error)
	GetProduct(ctx context.Context, sku int32) (GetProductRow, error)
}

var _ Querier = (*Queries)(nil)
