// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO loms.products (name, price)
VALUES ($1, $2)
RETURNING sku, name, price
`

type CreateProductParams struct {
	Name  string `json:"name"`
	Price int32  `json:"price"`
}

type CreateProductRow struct {
	Sku   int32  `json:"sku"`
	Name  string `json:"name"`
	Price int32  `json:"price"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.Price)
	var i CreateProductRow
	err := row.Scan(&i.Sku, &i.Name, &i.Price)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT sku, name, price
FROM loms.products
WHERE sku = $1
`

type GetProductRow struct {
	Sku   int32  `json:"sku"`
	Name  string `json:"name"`
	Price int32  `json:"price"`
}

func (q *Queries) GetProduct(ctx context.Context, sku int32) (GetProductRow, error) {
	row := q.db.QueryRow(ctx, getProduct, sku)
	var i GetProductRow
	err := row.Scan(&i.Sku, &i.Name, &i.Price)
	return i, err
}
